#!/usr/bin/env python3
"""
Combined Document Generator
Creates merged Web + Application versions of all document types:
- Combined-Pricing-Calculator.xlsx (Web + App sheets merged)
- Combined-Client-Proposal.docx
- Combined-Requirements-Complete-Guide.md
- Combined-Pricing-Parameters.md
- Combined-Client-Questionnaire.md
- Combined-Project-Checklist.md
- Combined-Pricing-Module-Overview.md
- Combined-Pricing-Quick-Guide.md
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMBINED_DIR = ROOT / "combined"
COMBINED_DIR.mkdir(exist_ok=True)


# ─── Markdown Merger ────────────────────────────────────────────────────────

def strip_h1(text: str) -> str:
    """Remove the first H1 heading from a markdown document."""
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.strip().startswith("# "):
            lines.pop(i)
            while i < len(lines) and not lines[i].strip():
                lines.pop(i)
            break
    return "\n".join(lines).strip()


def merge_markdown(app_path: Path, web_path: Path, out_path: Path, title: str, description: str):
    """Merge two markdown files (app + web) into one combined document."""
    app_text = app_path.read_text(encoding="utf-8", errors="replace").strip()
    web_text = web_path.read_text(encoding="utf-8", errors="replace").strip()

    app_body = strip_h1(app_text)
    web_body = strip_h1(web_text)

    combined = f"""# {title}

> {description}

> **Scope:** This document covers both **Web / Website Projects** and **Mobile Application Projects**. Use the relevant sections for your client's project type.

---

## 🌐 Part 1: Website / Web Application

---

{web_body}

---

## 📱 Part 2: Mobile Application

---

{app_body}
"""
    out_path.write_text(combined, encoding="utf-8")
    print(f"  [COMBINED-MD] Created: {out_path.relative_to(ROOT)}")


# ─── Excel Merger ───────────────────────────────────────────────────────────

def merge_excel(app_path: Path, web_path: Path, out_path: Path, title: str):
    """Merge Web and App Excel files into a single workbook with prefixed sheets."""
    import openpyxl
    from openpyxl.styles import PatternFill, Font, Alignment

    app_wb = openpyxl.load_workbook(app_path, data_only=True)
    web_wb = openpyxl.load_workbook(web_path, data_only=True)

    combined_wb = openpyxl.Workbook()
    combined_wb.remove(combined_wb.active)

    # Summary sheet
    summary_ws = combined_wb.create_sheet("Combined Summary", 0)
    header_fill = PatternFill(start_color="0F172A", end_color="0F172A", fill_type="solid")
    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=12)
    cell_font = Font(name="Calibri", size=11)
    center_align = Alignment(horizontal="center", vertical="center", wrap_text=True)

    summary_ws.append([title])
    summary_ws.append(["Combines pricing modules for both Website and Mobile Application projects."])
    summary_ws.append([])
    summary_ws.append(["Section", "Description", "Source Sheets"])
    summary_ws.append(["WEB - Website Pricing", "All website project pricing line items", ", ".join(web_wb.sheetnames)])
    summary_ws.append(["APP - Application Pricing", "All mobile app project pricing line items", ", ".join(app_wb.sheetnames)])
    summary_ws.append([])
    summary_ws.append(["Generated by:", "Client Requirement Analysis — Combined Document Suite"])

    for row_idx, row in enumerate(summary_ws.iter_rows(min_row=1, max_row=8), start=1):
        for cell in row:
            cell.font = header_font if row_idx in (1, 4) else cell_font
            if row_idx == 1:
                cell.fill = PatternFill(start_color="1E3A5F", end_color="1E3A5F", fill_type="solid")
            elif row_idx == 4:
                cell.fill = header_fill
                cell.alignment = center_align

    summary_ws.column_dimensions["A"].width = 35
    summary_ws.column_dimensions["B"].width = 55
    summary_ws.column_dimensions["C"].width = 40

    def copy_sheets(source_wb, prefix, fill_color):
        fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")
        bold_white = Font(name="Calibri", bold=True, color="FFFFFF", size=11)

        for sheet_name in source_wb.sheetnames:
            src_ws = source_wb[sheet_name]
            dest_name = f"{prefix} - {sheet_name}"[:31]
            dest_ws = combined_wb.create_sheet(dest_name)

            for col_letter, col_dim in src_ws.column_dimensions.items():
                dest_ws.column_dimensions[col_letter].width = col_dim.width
            for row_num, row_dim in src_ws.row_dimensions.items():
                dest_ws.row_dimensions[row_num].height = row_dim.height

            for row in src_ws.iter_rows():
                for cell in row:
                    dest_cell = dest_ws.cell(row=cell.row, column=cell.column)
                    dest_cell.value = cell.value
                    if cell.has_style:
                        try:
                            dest_cell.font = cell.font.copy()
                            dest_cell.border = cell.border.copy()
                            dest_cell.fill = cell.fill.copy()
                            dest_cell.number_format = cell.number_format
                            dest_cell.alignment = cell.alignment.copy()
                        except Exception:
                            pass

            # Insert prefix header row at top
            dest_ws.insert_rows(1)
            h = dest_ws.cell(row=1, column=1)
            h.value = f"{prefix}: {sheet_name}"
            h.fill = fill
            h.font = bold_white
            h.alignment = Alignment(horizontal="left", vertical="center")

    copy_sheets(web_wb, "WEB", "1E3A5F")
    copy_sheets(app_wb, "APP", "1E3D2F")

    combined_wb.save(out_path)
    print(f"  [COMBINED-XLSX] Created: {out_path.relative_to(ROOT)}")


# ─── DOCX Merger ────────────────────────────────────────────────────────────

def merge_docx(app_path: Path, web_path: Path, out_path: Path, title: str, description: str):
    """Merge Web and App DOCX files into one combined Word document."""
    import docx
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from lxml import etree
    import copy

    combined = docx.Document()

    style = combined.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    title_h = combined.add_heading(title, level=1)
    title_h.alignment = WD_ALIGN_PARAGRAPH.CENTER

    combined.add_paragraph(description)
    combined.add_paragraph(
        "Scope: This document covers both Website / Web Application and Mobile Application projects. "
        "Use the relevant section for your client's project type."
    )
    combined.add_page_break()

    def copy_doc_body(src_path: Path, section_heading: str, color: tuple):
        h = combined.add_heading(section_heading, level=1)
        if h.runs:
            h.runs[0].font.color.rgb = RGBColor(*color)

        src_doc = docx.Document(src_path)
        first_para_skipped = False
        for para in src_doc.paragraphs:
            # Skip the first H1 (title) from source document
            if not first_para_skipped and para.style.name.startswith("Heading 1"):
                first_para_skipped = True
                continue
            new_para = combined.add_paragraph(para.text, style=para.style.name if para.style.name in combined.styles else "Normal")
            for run, src_run in zip(new_para.runs, para.runs):
                run.bold = src_run.bold
                run.italic = src_run.italic
                run.underline = src_run.underline

    copy_doc_body(web_path, "Part 1: Website / Web Application", (0x1E, 0x3A, 0x5F))
    combined.add_page_break()
    copy_doc_body(app_path, "Part 2: Mobile Application", (0x1E, 0x3D, 0x2F))

    combined.save(out_path)
    print(f"  [COMBINED-DOCX] Created: {out_path.relative_to(ROOT)}")


# ─── Main ───────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("[COMBINED] Generating Combined Web + App Document Suite")
    print("=" * 60)

    COMBINED_DIR.mkdir(exist_ok=True)

    # 1. Pricing Calculator (XLSX)
    merge_excel(
        app_path=ROOT / "Template" / "excel template" / "Application-Pricing-Calculator.xlsx",
        web_path=ROOT / "Template" / "excel template" / "Website-Pricing-Calculator.xlsx",
        out_path=COMBINED_DIR / "Combined-Pricing-Calculator.xlsx",
        title="Combined Web + App Pricing Calculator"
    )

    # 2. Client Proposal (DOCX)
    merge_docx(
        app_path=ROOT / "Template" / "word template" / "Application-Client-Proposal.docx",
        web_path=ROOT / "Template" / "word template" / "Website-Client-Proposal.docx",
        out_path=COMBINED_DIR / "Combined-Client-Proposal.docx",
        title="Combined Web + App Client Proposal",
        description="Full-stack client proposal covering both website and mobile application scope, pricing, and deliverables."
    )

    # 3. Requirements Complete Guide (MD)
    merge_markdown(
        app_path=ROOT / "docs" / "application" / "Application-Requirements-Complete-Guide.md",
        web_path=ROOT / "docs" / "website" / "Website-Requirements-Complete-Guide.md",
        out_path=COMBINED_DIR / "Combined-Requirements-Complete-Guide.md",
        title="Combined Web + App Requirements Complete Guide",
        description="Comprehensive requirements guide covering both website/web application and mobile application projects in a single reference document."
    )

    # 4. Pricing Parameters (MD)
    merge_markdown(
        app_path=ROOT / "docs" / "application" / "Application-Pricing-Parameters.md",
        web_path=ROOT / "docs" / "website" / "Website-Pricing-Parameters.md",
        out_path=COMBINED_DIR / "Combined-Pricing-Parameters.md",
        title="Combined Web + App Pricing Parameters",
        description="Unified pricing parameters reference covering all line items, cost factors, and configurable variables for both website and mobile application engagements."
    )

    # 5. Client Questionnaire (MD)
    merge_markdown(
        app_path=ROOT / "Questionnaire" / "application" / "Application-Client-Questionnaire.md",
        web_path=ROOT / "Questionnaire" / "website" / "Website-Client-Questionnaire.md",
        out_path=COMBINED_DIR / "Combined-Client-Questionnaire.md",
        title="Combined Web + App Client Questionnaire",
        description="All-in-one client discovery questionnaire. Send this when a client needs both a website and a mobile application, or when you want a single intake form to qualify both scopes."
    )

    # 6. Project Checklist (MD)
    merge_markdown(
        app_path=ROOT / "checklists" / "Application-Project-Checklist.md",
        web_path=ROOT / "checklists" / "Website-Project-Checklist.md",
        out_path=COMBINED_DIR / "Combined-Project-Checklist.md",
        title="Combined Web + App Project Checklist",
        description="Full-scope project delivery checklist covering all phases for both website and mobile application projects from discovery to launch."
    )

    # 7. Pricing Module Overview (MD)
    merge_markdown(
        app_path=ROOT / "overview" / "Application-Pricing-Module-Overview.md",
        web_path=ROOT / "overview" / "Website-Pricing-Module-Overview.md",
        out_path=COMBINED_DIR / "Combined-Pricing-Module-Overview.md",
        title="Combined Web + App Pricing Module Overview",
        description="Consolidated pricing module overview documenting all pricing tiers, methodology, and structure for both website and mobile application engagements."
    )

    # 8. Pricing Quick Guide (MD)
    merge_markdown(
        app_path=ROOT / "overview" / "Application-Pricing-Quick-Guide.md",
        web_path=ROOT / "overview" / "Website-Pricing-Quick-Guide.md",
        out_path=COMBINED_DIR / "Combined-Pricing-Quick-Guide.md",
        title="Combined Web + App Pricing Quick Reference Guide",
        description="Quick-reference pricing guide for full-stack engagements covering both website and mobile application pricing tiers at a glance."
    )

    print("\n" + "=" * 60)
    print(f"[SUCCESS] All combined documents generated in: {COMBINED_DIR}")
    print("=" * 60)
    print("\nFiles created:")
    for f in sorted(COMBINED_DIR.iterdir()):
        size_kb = f.stat().st_size / 1024
        print(f"  {f.name}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
